language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode9.4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:cginternals/backports-ppa'
    packages:
      - g++-7
      - gcc-7
      - libcurl4-openssl-dev
      - libglbinding-dbg
      - libglbinding-dev
      - libglu1-mesa-dev
      - libsdl2-dev
      - libssl-dev
      - libx11-dev
      - libxcursor-dev
      - xorg-dev
      - zlib1g-dev

cache:
  directories:
    - "$HOME/.local"

install:
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  -  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl openssl sdl2; fi

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir cbuild && cd cbuild
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DDECAF_BUILD_TOOLS=ON -DDECAF_FFMPEG=OFF -DDECAF_VULKAN=OFF ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DDECAF_BUILD_TOOLS=ON -DDECAF_GL=OFF -DDECAF_FFMPEG=OFF -DDECAF_VULKAN=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..; fi
  - make -j4
